Juan SGW 625 unify evm providers
StardustCollective/stargazer-wallet-ext pull request #420
Opened 2023-05-10 15:01 UTC by juanolmedo1

Ticket: [SGW-625](https://constellationnetwork.atlassian.net/browse/SGW-625)

2023-05-11 01:15 UTC, juandavidkincaid requested changes
I think changes, in general, are in accordance with the ticket (solve it), but unfortunately, this time it is really confusing to navigate through the codebase, I know the codebase per se is messy, but I would highly suggest cleanup things while you add features, or try to.

And definitely please address the uses of `StargazerChain` and `StargazerProvider(enum)`.

2023-05-11 01:15 UTC, juandavidkincaid commented on source/scripts/common/availableChainMethods.ts
> +  chain: StargazerChain | StargazerProvider;
As well keeping an union here seems odd to me for some reason.

2023-05-11 01:15 UTC, juandavidkincaid commented on source/scripts/common/chains.ts
>    ETHEREUM = 'ethereum',
I just followed the references of `StargazerChain` and `StargazerProvider`, I may think you need to cleanup/reorganize uses for both as I think you're mixing things up with those.

2023-05-11 01:15 UTC, juandavidkincaid commented on source/scripts/Background/dappRegistry/dappRegistry.ts
> +    chain: '*' | StargazerChain | StargazerProvider,
Don't like this unions.

2023-05-11 01:15 UTC, juandavidkincaid commented on source/scripts/Background/controllers/WalletController.ts
>            StargazerChain.ETHEREUM,
Yeap I think this is mixed. (`StargazerProvider` vs `StargazerChain`)

2023-05-11 01:15 UTC, juandavidkincaid commented on source/scenes/settings/Networks/Networks.container.tsx
> +      await walletController.switchActiveNetwork(networkId);
It seems this `await` is not necessary.

2023-05-11 14:26 UTC, juanolmedo1 commented on source/scripts/Provider/EVMProvider.ts
>          chainLabel
Yeah, it's intended. The chain value is used to select the expected provider: Constellation or Ethereum.
I'll update the property name to `provider`

2023-06-13 18:15 UTC, juandavidkincaid approved these changes
Looks nice :]]]], let me know when it is deployed on chrome.

2023-06-15 19:03 UTC, merged